### ISSUE TITLE
Czemu nie dziala mi ten plugin?

### ISSUE THREAD

**Issue by vishjak** [pawelkuwa/DropSMP#26]
[20:48:14] [Server thread/INFO]: [DropSMP] Enabling DropSMP v1.4alpha2
[20:48:14] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: dropsmp [1.1]
[20:48:14] [Server thread/INFO]: Znaleziono PlaceholderAPI, tworzÄ™ placeholdery...
[20:48:14] [Server thread/INFO]: [DropSMP] Plugin zostaĹ‚ wĹ‚Ä…czony!
[20:48:15] [Server thread/ERROR]: Error occurred while enabling DropSMP v1.4alpha2 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "tombstones" is null
	at me.wisnia.dropsmp.DropSMP.onEnable(DropSMP.java:142) ~[DropSMP-1.4alpha2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[20:48:15] [Server thread/INFO]: [DropSMP] Disabling DropSMP v1.4alpha2
[20:48:15] [Server thread/INFO]: [DropSMP] Plugin zostaĹ‚ wyĹ‚Ä…czony

**Comment by pawelkuwa** [comment]
Jutro postaram się zajrzeć, ale u mnie błąd nie występuje. Spróbuj zmienić wersję silnika na papermc 1.18.2

**Comment by vishjak** [comment]
Zmienilem i jest ten sam błąd

**Comment by pawelkuwa** [comment]
Dziwne, podaj jeszcze listę wszystkich pluginów z których korzystasz na serwerze.

**Comment by pawelkuwa** [comment]
Zaktualizuj plugin do https://github.com/pawelkuwa/DropSMP/releases/tag/1.5.1, jeżeli wystąpi błąd wyślij go znowu tutaj. Jeżeli plugin załaduje się poprawnie, daj znać.
